### DISCUSSION TITLE
🎉 Context Generator 1.21.1 Released!

### DISCUSSION THREAD

**Discussion by butschster** [context-hub/generator#128] [Announcements]
# 🎉 Context Generator 1.21.1 Released!

Hey everyone! We’ve just dropped a new version of **Context Generator – 1.21.1**. Here’s what’s new and improved:

---

## 🚀 MacOS Builds Added

Good news for Mac users!  
We’ve added GitHub workflows to build binaries for **MacOS**:
- ✅ **amd64**
- ✅ **arm64 (Apple Silicon)**  
Now you can easily run Context Generator on any Mac.

---

## 🪟 Windows Build Fixed

We fixed issues with the Windows build.  
Now you can run Context Generator on Windows without errors.

**Example config for Windows:**
```json
{
  "mcpServers": {
    "ctx": {
      "command": "C:\\Path\\To\\ctx.exe",
      "args": [
        "server",
        "-cC:\\Path\\To\\Project"
      ]
    }
  }
}
```

This config will:
- Run `ctx.exe`
- Start in **server mode**
- Use config from `C:\Path\To\Project`

📄 See docs here https://docs.ctxgithub.com/mcp-server.html#setting-up

---

## ✨ Better Git Diff Rendering

We made Git diff rendering more flexible.  
You can now use a simple or full configuration:

**Simple:**
```yaml
sources:
  - type: git_diff
    render: llm
```

**Full:**
```yaml
sources:
  - type: git_diff
    render:
      strategy: llm
      showStats: true
```

📄 See docs here https://docs.ctxgithub.com/sources/git-diff-source.html#render-configuration

---

## 🧩 Schema Autocomplete for Configs

Now when you run `ctx init`, the config will include a **$schema** property.  
This helps you get **autocomplete and validation** in your IDE.

Example:
```yaml
$schema: 'https://raw.githubusercontent.com/context-hub/generator/refs/heads/main/json-schema.json'
documents:
  ...
```

---

## 💬 Prompt Configuration Support

You can now define and use **prompts** in your config.  
Prompts are ready-to-use conversation templates for LLMs.

**Example:**
```yaml
prompts:
  - id: generate-controller
    description: "Generate a controller for an entity"
    schema:
      properties:
        entityName:
          description: "Entity name (e.g. User)"
      required:
        - entityName
    messages:
      - role: system
        content: "You are a PHP code generator."
      - role: assistant
        content: "Tell me the entity name."
      - role: user
        content: "Generate a controller for {{entityName}}."
```

📄 See docs here https://docs.ctxgithub.com/mcp/prompts.html

---

## 🌍 Import Config from Remote Sources

You can now import config parts from:
- Local files
- URLs
- GitHub Gists

Example:
```yaml
import:
  - path: services/api/context.yaml
  - url: https://example.com/context-configs/api-prompts.yaml
  - url: https://gist.githubusercontent.com/butschster/1b7e597691cc1a6476b15dc120ecbddb/raw/prompts.yaml
```

This helps you:
✅ Reuse prompts  
✅ Share configs  
✅ Keep everything modular & clean

**You can check an example of shareable prompts here:**  
👉 Example Gist https://gist.github.com/butschster/1b7e597691cc1a6476b15dc120ecbddb

---

**Update now and enjoy the new features!**  
If you have feedback — let us know. We’re building this tool for you. 😊
