### DISCUSSION TITLE
🎉 Context Generator 1.23.0 Released!

### DISCUSSION THREAD

**Discussion by butschster** [context-hub/generator#157] [Announcements]
### 🔄 Platform-Specific Binary Downloads

**What's New:**
- Automatic platform and architecture detection for the `self-update` command
- Downloads the appropriate binary based on user's system (linux/darwin/windows and amd64/arm64)

### 🔧 Custom Variables in Configuration Files

**What's New:**
- Define variables once and reference them throughout your configuration
- Support for environment-specific configurations without duplication

**Why It's Cool:**
- Maintain DRY (Don't Repeat Yourself) configurations
- Easily switch between environments (development, staging, production)
- Create more maintainable and readable configuration files

**Example:**
```yaml
variables:
  version: 1.0.0
  environment: development
  project_name: Context Generator
  base_path: docs/{{environment}}

documents:
  - description: 'API Documentation'
    outputPath: {{base_path}}/api/{{project_name}}-{{version}}.md
    sources:
      - type: file
        path: src/api/*.php
  
  - description: 'User Guide'
    outputPath: {{base_path}}/guide/{{project_name}}-{{version}}.md
    sources:
      - type: text
        content: |
          # {{project_name}} v{{version}}
          Environment: {{environment}}
          
          ## Getting Started
          This guide will help you get started with the {{project_name}}.
```

### 🛠️ Custom Tools Framework

**What's New:**
- Define and execute project-specific tools directly from configuration files
- Support for command chains with arguments and environment variables
- Integrated with the Context Generator CLI

**Why It's Cool:**
- Standardize project tooling across teams
- Execute complex operations with simple commands
- Automate repetitive tasks specific to your project

**Example:**
```yaml
tools:
  - id: lint
    description: 'Lint and fix code style issues'
    commands:
      - cmd: composer
        args: ['cs:fix']
        
  - id: test-and-build
    description: 'Run tests and build documentation'
    commands:
      - cmd: vendor/bin/phpunit
        args: ['--testsuite', 'unit']
      - cmd: ctx
        args: ['generate', '--config=docs.yaml']
        env:
          CTX_ENV: production
          
  - id: deploy
    description: 'Deploy documentation to server'
    commands:
      - cmd: rsync
        args: ['-avz', 'docs/', 'user@server:/var/www/docs/']
```

### 🔧 Self-Update Command Fixes

**What's New:**
- Fixed the "Text file busy" error that occurred when updating the currently running binary
- Implemented robust binary updating system with platform-specific strategies
- Added background scripts that update binaries after the process exits

### 📊 Generate Command Output Readability

**Before:**
```
 [INFO] Compiling Project structure overview...
                                                                            
 [OK] Document compiled into project-structure.md                           
                                                                            
 [INFO] Compiling Core Interfaces...
                                                                            
 [OK] Document compiled into core/interfaces.md                             
                                                                            
 [INFO] Compiling Modifiers System...
                                                                            
 [WARNING] Document compiled into modifiers/modifiers-core.md with errors   
                                                                            
 * Error in FileSource: Some directories or files contain invalid paths
```

**After:**
```
 ✓ Source Token counter [sources/token-counter.md].......................................................................
 ✓ Document source renderer [sources/source-renderer.md].................................................................
 ! Modifiers System [modifiers/modifiers-core.md]........................................................................
    ✗ Error in FileSource: Some directories or files contain invalid paths:

 ✓ PHP Content Modifiers [modifiers/php-modifiers.md]....................................................................
 ! Sanitizer Modifier [modifiers/sanitizer.md]...........................................................................
    ✗ Error in FileSource: Some directories or files contain invalid paths:

 ✓ Path Filtering Utilities [utilities/path-filters.md]..................................................................
 ✓ Tree Building Utilities [utilities/tree-builder.md]...................................................................
```

### 🪟 Windows Path Normalization

**What's New:**
- Enhanced path handling capabilities to better support Windows-style paths
- Improved TreeBuilder components for cross-platform compatibility

---

## What's Changed
* Platform-Specific Binary Downloads by @butschster in https://github.com/context-hub/generator/pull/141
* Add support for custom variables in configuration files by @butschster in https://github.com/context-hub/generator/pull/144
* Windows path normalization improvements in tree builder by @butschster in https://github.com/context-hub/generator/pull/147
* Enhanced Logger Injection with PHP Attributes by @butschster in https://github.com/context-hub/generator/pull/148
* Improved Generate Command Output Readability by @butschster in https://github.com/context-hub/generator/pull/149
* Git Components Refactoring by @butschster in https://github.com/context-hub/generator/pull/151
* Added feature tests for document compiler by @butschster in https://github.com/context-hub/generator/pull/155
* Add custom tools configuration and execution support by @butschster in https://github.com/context-hub/generator/pull/156

**Full Changelog**: https://github.com/context-hub/generator/compare/1.22.0...1.23.0
