### DISCUSSION TITLE
CTX 1.26.0 Release Notes 🎉

### DISCUSSION THREAD

**Discussion by butschster** [context-hub/generator#197] [Announcements]
## CTX 1.26.0 Release Notes 🎉

We're excited to announce version **1.26.0**, packed with new features, enhancements, and documentation updates. This release focuses on improved GitLab integration, prompt tagging and filtering, and streamlined CLI interactions for MCP tools.

#### 🌟 GitLab Source Integration

The new GitLab source component mirrors the existing GitHub functionality, providing robust integration to fetch code and documentation directly from GitLab repositories.

> **Read more** in a documentation section [GitLab Source](https://docs.ctxgithub.com/sources/gitlab-source.html)

**Example Configuration:**

```yaml
documents:
  - description: Self-hosted GitLab Documentation
    outputPath: docs/self-hosted-gitlab.md
    sources:
      - type: gitlab
        description: Self-hosted GitLab Project
        repository: group/project
        branch: main
        server:
          url: https://gitlab.test.com
          token: ${TEST_GITLAB_TOKEN}
        sourcePaths:
          - src
        filePattern: "*.php"
```

#### 🔖 Advanced Prompt Tagging and Filtering

Organize and selectively import prompts more efficiently with advanced tagging and filtering capabilities, streamlining your workflow and reducing clutter in your prompt registries.

> **Read more** in a documentation section [Prompts Import](https://docs.ctxgithub.com/mcp/prompts.html#import)

**Example Configuration:**

```yaml
prompts:
  - id: creative-writing
    description: "Helps generate creative writing pieces"
    tags: ["writing", "creative", "content-generation"]
    messages:
      - role: user
        content: "You are a creative writing assistant..."
```

1. **Prompt Tagging**: Ability to assign tags to prompts in the YAML configuration
   ```yaml
   prompts:
     - id: creative-writing
       description: "Helps generate creative writing pieces"
       tags: ["writing", "creative", "content-generation"]
   ```

2. **ID-Based Import Filtering**: Ability to import specific prompts by their IDs
   ```yaml
   import:
     - url: "https://prompts-repository.example.com/prompts.yaml"
       filter:
         ids: ["python-helper", "php-debug", "js-refactor"]
   ```

3. **Tag-Based Import Filtering**: Support for filtering by tags with include/exclude logic
   ```yaml
   import:
     - path: "./local-prompts.yaml"
       filter:
         tags:
           include: ["coding", "debugging"]
           exclude: ["advanced"]
         match: "any"  # can be "all" for AND logic
   ```

#### 📋 CLI Command for Listing Prompts

Discover and explore available prompts directly from the command line, simplifying prompt management and selection.

> **Read more** in a documentation section [Command Reference
](https://docs.ctxgithub.com/getting-started/command-reference.html#list-available-prompts)

**CLI Usage Examples:**

```bash
# List all prompts in table format
ctx prompts:list

# Show detailed information with arguments
ctx prompts:list --detailed
# or
ctx prompts -d

# Filter prompts by tags
ctx prompts:list --tag api --tag documentation
# or
ctx prompts -t api -t documentation

# Exclude prompts with specific tags
ctx prompts:list --exclude-tag experimental
# or
ctx prompts -x experimental

# Filter prompts by ID
ctx prompts:list --id system-prompt --id user-query
# or
ctx prompts -p system-prompt -p user-query
```

#### 🖥️ CLI Tool Execution

Enhance your development and testing workflow by directly executing MCP tools from the command line, offering interactive prompts and simplified argument validation.

> **Read more** in a documentation section [Command Reference
](https://docs.ctxgithub.com/getting-started/command-reference.html#list-available-tools)

**CLI Usage Example:**

```bash
# List available tools
ctx tool:list

# Run a specific tool interactively
ctx tool:run lint-code

# Run with arguments provided via command line
ctx tool:run lint-code --arg path=src/MyClass.php --arg fix=true
```

Thank you for using CTX! Your feedback and contributions help us make this tool even better. 🎈

---

## What's Changed
* GitLab Source Component by @butschster in https://github.com/context-hub/generator/pull/190
* Modular Configuration Merger System by @butschster in https://github.com/context-hub/generator/pull/192
* Add prompt tagging and import filtering system by @butschster in https://github.com/context-hub/generator/pull/195
* MCP Tool CLI Commands by @butschster in https://github.com/context-hub/generator/pull/196

## New Contributors
* @eltociear made their first contribution in https://github.com/context-hub/generator/pull/188

**Full Changelog**: https://github.com/context-hub/generator/compare/1.25.0...1.26.0

<hr /><em>This discussion was created from the release <a href='https://github.com/context-hub/generator/releases/tag/1.26.0'>1.26.0</a>.</em>
