### DISCUSSION TITLE
Automatic tools and context generation

### DISCUSSION THREAD

**Discussion by butschster** [context-hub/generator#202] [Ideas]
Check this out 👉 [https://context7.com/](https://context7.com)  
It gives your LLM (Claude, Cursor, etc.) **real Laravel docs** — no outdated stuff, just clean and fresh info from source.

Let’s say you wanna search for routing in Laravel docs — just use this link:  
🔍 `https://context7.com/laravel/docs?topic=routing&tokens=500`

You point to the repo (`laravel/docs`), set the topic (`routing`), and max tokens (`500`).  
Boom! Docs ready to copy into your AI tool.

---

But here’s the **coolest part** — you don’t need to write configs for tools or context files yourself.  
Just **ask the LLM**, and it will build it for you!

### 🛠️ Example instruction:

> 🗒️ *Instruction to LLM:*  
> _There is a link `https://context7.com/laravel/docs/llms.txt?topic=route` to search context from docs, in this example it's Laravel docs. Provide a tool for it._

### 🤖 What LLM replied:
```yaml
tools:  
  - id: laravel-docs  
    description: "Fetch Laravel documentation based on a provided topic"  
    type: http  
    schema:  
      properties:  
        topic:  
          type: string  
          description: "Documentation topic to retrieve (e.g., 'routing', 'controllers', 'models')"  
      required:  
        - topic  
    requests:  
      - url: "https://context7.com/laravel/docs/llms.txt"  
        method: GET  
        query:  
          topic: "{{topic}}"  
        headers:  
          Accept: "text/plain"
```

---

And you can also generate context docs the same way!

### 📄 Example instruction:

> 🗒️ *Instruction to LLM:*  
> _There is a link `https://context7.com/laravel/docs/llms.txt?topic=route` to search context from docs, in this example it's Laravel docs. Provide an example of url source for it for documents._

### 🤖 What LLM replied:
```yaml
documents:
  - description: Laravel Documentation
    outputPath: docs/laravel-documentation.md
    sources:
      - type: url
        description: "Laravel official documentation"
        urls:
          - https://context7.com/laravel/docs/llms.txt?topic=routing
          - https://context7.com/laravel/docs/llms.txt?topic=controllers
          - https://context7.com/laravel/docs/llms.txt?topic=models
        headers:
          Accept: "text/plain"
          User-Agent: "CTX Documentation Generator"
        tags:
          - laravel
          - documentation
          - reference
```

---

💡 So yeah — LLM can build tools *for itself* using CTX and JSON schema.  
You just write simple instructions, and it does the rest.  
No need to guess or dig through docs yourself anymore!
