### ISSUE TITLE
Remote Configuration Import

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#113]
Context Generator currently supports basic configuration imports from local filesystem sources. This proposal extends the import functionality to include remote sources like GitHub repositories, Composer packages, and remote URLs, with a particular focus on making MCP prompts more accessible and shareable.

## The Problem

Currently, developers using Context Generator with MCP need to:
1. Manually create prompt configurations
2. Cannot easily share or reuse prompt configurations between projects
3. Have limited ability to leverage community-created prompt libraries

## The Solution

Enhance the import system to support multiple source types, allowing developers to:
1. Import MCP prompts from GitHub repositories
2. Leverage prompt configurations from Composer packages
3. Reference remote configuration files via URLs
4. Selectively import only specific documents from any source

## Benefits

- **Reusability**: Create prompt repositories once, use them in multiple projects
- **Community Sharing**: Enable a community ecosystem of prompt libraries
- **Standardization**: Promote best practices through shared prompt configurations
- **Selective Imports**: Import only what you need, keeping configurations lean
- **Version Control**: Reference specific versions/branches of remote repositories

### Configuration Format

```yaml
import:
  # Local import (current implementation)
  - path: services/api/context.yaml
    type: local # default, can be omitted
  
  # GitHub import
  - path: butschster/ctx-prompts/prompts/refactoring.yaml
    type: github
    ref: main # optional, defaults to main/master
    token: ${GITHUB_TOKEN} # optional, for private repos
  
  # Composer package import
  - path: vendor/butschster/ctx-prompts/prompts/refactoring.yaml
    type: composer
    
  # URL import
  - path: https://example.com/context-configs/api-prompts.yaml
    type: url
    headers: # optional HTTP headers
      Authorization: "Bearer ${API_TOKEN}"

  # Selective import (works with any source type)
  - path: butschster/ctx-prompts/prompts/all.yaml
    type: github
    docs: 
      - refactoring/extract-method.md
      - refactoring/rename-class.md
```

### MCP Prompt Configuration Example

Let's define how MCP prompts would be configured in the YAML format:

```yaml
prompts:
  - id: context-list
    description: "List available contexts"
    messages:
      - role: assistant
        content: "I'm a context generator. I can provide you with a list of available contexts."
      - role: user
        content: "Provide list of available contexts in JSON format"
  
  - id: refactor-extract-method
    description: "Extract a method from existing code"
    messages:
      - role: assistant
        content: "I can help you refactor code by extracting methods. Please provide the code you want to refactor."
      - role: user
        content: "Extract the highlighted code into a separate method with the following signature: ```php\nprivate function calculateTotal(array $items): float\n```"
      - role: assistant
        content: "I'll extract that code into a separate method. Here's my approach:"
```
