### ISSUE TITLE
Add macOS Build Support

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#115]
We've received numerous requests from developers asking for native macOS binaries . Currently, we only provide Linux and Windows binaries, forcing macOS users to use the PHAR version which requires PHP installation.

### Current State
- Linux builds are available for both amd64 and arm64 architectures
- Windows build is available for amd64 architecture
- **No macOS support** is currently available for native binaries

### Requested Feature
- Add GitHub Actions workflow to build native macOS binaries
- Support both `amd64` and `arm64` architectures
- Include these binaries in future releases

### User Impact
This feature would significantly improve the experience for macOS developes. They currently have to install PHP separately or use alternative methods to run **ctx**.

### Help Needed
If anyone has experience with GitHub Actions for macOS builds (especially with Static PHP CLI), any help or guidance would be greatly appreciated. We've attached a draft workflow file that needs review and testing.

**Comment by joaooliveira10** [comment]
Para adicionar binários nativos do macOS (amd64/arm64) via GitHub Actions, você pode usar este fluxo de trabalho como referência:


```yaml
name: Build macOS Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: ${{ contains(matrix.arch, 'arm64') && 'macos-latest-arm64' || 'macos-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, flex
        
      - name: Install Dependencies
        run: |
          brew install automake libtool pkg-config openssl@3

      - name: Build Static PHP CLI
        run: |
          # Comandos específicos para sua build estática
          ./configure --enable-static \
            --prefix=/usr/local \
            --with-openssl=$(brew --prefix openssl@3)
          
          make -j$(nproc)
          
          # Renomear binário com arquitetura
          mv php-bin bin/ctx-${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ctx-macos-${{ matrix.arch }}
          path: bin/ctx-${{ matrix.arch }}

  release:
    needs: build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Universal Binary
        if: ${{ contains(matrix.arch, 'arm64') }}
        run: |
          lipo -create \
            artifacts/ctx-x86_64 \
            artifacts/ctx-arm64 \
            -output ctx-universal

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/ctx-x86_64
            artifacts/ctx-arm64
            ctx-universal
```

**Principais pontos:**

**Matriz de Arquiteturas:**
Usa uma estratégia de matriz para construir ambas as arquiteturas (x86_64 e arm64) simultaneamente.

**Runners Específicos:**
macos-latest-arm64 para ARM64 e macos-latest para Intel.

**Build Estático:**
Exemplo de configuração para compilação estática do PHP com OpenSSL.

**Universal Binary:**
Opcionalmente cria um binário universal usando lipo para compatibilidade total.

**Integração com Releases:**
Anexa os binários ao GitHub Release automaticamente.

Recomendo testar com tags semânticas (ex: v1.0.0-macbeta) antes de liberar oficialmente. Verifique também as dependências específicas do seu projeto na etapa de build.
