### ISSUE TITLE
Invalid relative paths

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#130]
```
documents:
  - description: 'Значимые части backend api приложения на yii2'
    outputPath: backend-structure.md
    overwrite: true
    sources:
      - type: file
        sourcePaths:
          - /../../anicrm-10/backend/config
          - /../../anicrm-10/backend/modules/v1
          - /../../anicrm-10/backend/web
          - /../../anicrm-10/common
          - /../../anicrm-10/console/config
          - /../../anicrm-10/console/controllers
          - /../../anicrm-10/console/migrations
          - /../../anicrm-10/yii2-modules-dev/yii2-crudapi/src
          - /../../anicrm-10/frontend/config
          - /../../anicrm-10/frontend/controllers
          - /../../anicrm-10/frontend/models
          - /../../anicrm-10/frontend/views
          - /../../anicrm-10/frontend/web
        filePattern: '*.php'
        notPath: ['codeception-local.php','test-local.php','test.php']
      - type: file
        sourcePaths:
          - /../../anicrm-10/composer.json
```

`/../../` pattern does not work
