### ISSUE TITLE
Custom tools definition

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#142]
Adding a custom tools section would extend this functionality by enabling users to define and execute project-specific commands directly from the context configuration.

### Proposed Configuration Structure

```yaml
tools:
  - id: cs-fixer                     # Unique identifier for the tool
    description: 'Fix code style'    # Human-readable description
    type: run                        # Tool type (run = execute command)
    commands:                        # List of commands to execute
      - cmd: composer                # Command to run
        args:                        # Command arguments (array)
          - cs:fix
          - --dry-run
          - --diff
          - --ansi
          - --no-interaction
        workingDir: .                # Optional working directory (relative to project root)
        env:                         # Optional environment variables
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSER_HOME: /tmp/composer
```

### Use Cases

1. **Code Style Fixing**
   ```yaml
   tools:
     - id: cs-fixer
       description: 'Fix code style issues'
       type: run
       commands:
         - cmd: composer
           args: ['cs:fix']
   ```

2. **Static Analysis**
   ```yaml
   tools:
     - id: phpstan
       description: 'Run static analysis'
       type: run
       commands:
         - cmd: vendor/bin/phpstan
           args: ['analyse', 'src', '--level', '8']
   ```

3. **Multi-Step Processes**
   ```yaml
   tools:
     - id: test-suite
       description: 'Run full test suite with coverage'
       type: run
       commands:
         - cmd: composer
           args: ['install', '--no-dev']
         - cmd: vendor/bin/phpunit
           args: ['--coverage-html', 'coverage']
         - cmd: vendor/bin/infection
           args: ['--min-msi=80']
   ```

4. **Deployment**
   ```yaml
   tools:
     - id: deploy-staging
       description: 'Deploy to staging environment'
       type: run
       commands:
         - cmd: bash
           args: ['deploy.sh', 'staging']
           env:
             DEPLOY_TOKEN: "${STAGING_TOKEN}"
   ```

### Implementation Details

1. **Tool Types**
   - Initially support the `run` type for command execution
   - Future types could include `script` (for inline scripts), `http` (for API calls), etc.

2. **Command Execution**
   - Commands should be executed in sequence
   - Support for command piping and shell-style execution
   - Execution in the project root directory by default, with option to specify custom working directory

3. **Environment Variables**
   - Support for environment variables in commands and arguments
   - Allow passing of environment variables to the command

4. **Security Considerations**
   - Add environment variable to disable command execution: `MCP_TOOL_COMMAND_EXECUTION=false`
   - Consider adding permission controls for command execution
   - Validate commands before execution to prevent shell injection

5. **Output Handling**
   - Capture and return command output to the LLM
   - Option to stream output for long-running commands
   - Support for capturing exit codes and handling errors

### Example MCP Configuration

```json
{
  "mcpServers": {
    "ctx": {
      "command": "ctx",
      "args": [
        "server",
        "-c",
        "/path/to/project"
      ],
      "env": {
        "MCP_TOOL_COMMAND_EXECUTION": "true"
      }
    }
  }
}
```

### Environment Variable Controls

| Variable | Description | Default |
|----------|-------------|---------|
| `MCP_TOOL_COMMAND_EXECUTION` | Enable/disable command execution | `true` |
| `MCP_TOOL_MAX_RUNTIME` | Maximum runtime for a command in seconds | `30` |

**Comment by roxblnfk** [comment]
I think it should allow any shell command and the config might look like this:

```yaml
tools:
  - cmd: composer
    args:
      - cs:fix
      - --dry-run
      - --diff
      - --ansi
      - --no-interaction
    description: 'Fix code style'
```

And deny importing it from external sources. Only root file config.
