### ISSUE TITLE
Custom variables in configuration files

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#143]
Add support for defining custom variables directly in configuration files that can be used throughout the context definitions.

## Use Case
Users need the ability to centrally define variables like versions, environment names, API tokens, project names, etc., that can be referenced throughout the configuration file. This reduces repetition and makes it easier to update values in a single place.

## Example Usage
```yaml
variables:
  token: qwd-qwe123-1231
  version: 1.0.0
  environment: development
  project_name: Context Generator

prompts:
  - id: my-local-prompt
    description: My local prompt
    messages:
      - role: user
        content: |
          You are generating code for {{project_name}} v{{version}} in {{environment}}.
          Using token {{token}}.

documents:
  - description: 'Project documentation'
    outputPath: docs/{{environment}}/{{project_name}}-{{version}}.md
    sources:
      - type: text
        content: |
          # {{project_name}} v{{version}}
          Environment: {{environment}}
```

## Benefits
- Reduces duplication in configuration files
- Makes it easier to update shared values
- Supports dynamic path generation based on configuration
- Works with existing variable substitution syntax
- Integrates with environment variables but with higher priority
