### ISSUE TITLE
MCP source type

### ISSUE THREAD

**Issue by roxblnfk** [context-hub/generator#158]
Add a new `mcp` source type to CTX that leverages the MCP client to connect to an MCP server and perform operations to gather data for documentation generation. This implementation will support reading resources and calling tools.

### Defining MCP Servers in Settings

```yaml
# ctx.yaml
settings:
  mcp:
    servers:
      github:
        command: "ctx-server"
        args: ["--config", "/path/to/github/config"]
        env:
          GITHUB_TOKEN: "${GITHUB_TOKEN}"
      
      local:
        command: "wsl.exe"
        args: ["bash", "-c", "ctx server"]
        env:
          CTX_ENV: "development"

      cloud:
        url: "https://api.example.com/mcp"
        headers:
          Authorization: "Bearer ${API_TOKEN}"
```

### Using MCP Source in Documents

```yaml
# context.yaml
documents:
  - description: MCP Server Data
    outputPath: docs/mcp-data.md
    sources:
      # Using a pre-defined server
      - type: mcp
        description: "GitHub MCP Resources"
        server: github  # Reference to pre-defined server
        operation:
          type: readResource
          resources:
            - "file://project/src/Controller/HomeController.php"
            - "file://project/src/Service/UserService.php"
      
      # Alternatively, define server inline
      - type: mcp
        description: "Custom MCP Tool Results"
        server:
          command: "custom-mcp-server"
          args: ["--port", "8080"]
        operation:
          type: callTool
          toolName: "code-analyzer"
          arguments:
            path: "src/Controller"
            recursive: true
```

### Phase 1: Core Implementation (Current Scope)
1. Create `McpSource` class that implements the Source interface
2. Implement `McpSourceConfig` to handle and validate source configuration
3. Implement `McpServerRegistry` to manage pre-defined server configurations
4. Implement `McpConnection` to manage MCP client connections
5. Implement operation handlers:
   - `ReadResourceOperation` - Support reading multiple resources
   - `CallToolOperation` - Support calling tools with arguments

### File Structure
```
Source/MCP/
├── McpSource.php (Main source implementation)
├── McpSourceConfig.php (Configuration handler)
├── McpServerRegistry.php (Manages server configurations)
├── McpConnection.php (Connection manager)
└── Operations/
    ├── AbstractOperation.php (Base operation class)
    ├── ReadResourceOperation.php
    └── CallToolOperation.php
```

### Phase 2: Future Enhancements (Not in Current Scope)
1. Add support for additional operations:
   - `ListResources`
   - `ListTools`
   - `ListPrompts`
   - `GetPrompt`
2. Implement caching mechanisms for MCP connections
