### ISSUE TITLE
[Discussion] Add document type `catalog`

### ISSUE THREAD

**Issue by roxblnfk** [context-hub/generator#165]
## Description

Think about how we can expose a new document type like `catalog` or `library`, which will render a list of contexts or documents so that the LLM can load the required context by the specified path.

## Example

I want to compose these documents in a single context file `Guidelines` with an instruction like this: `There are best guidelines in the  context. Look at them and read those which are matched with your tasks.`

Sources:

```yaml
- description: How to write PHP code
  outputPath: guidelines/how-to-write-php-code.md
  sources:
    - type: url
      urls:
          - https://.../php-best-practices/
          - https://.../php-8.1/
          - https://.../php-spiral-3.14/
- description: How to write PHP tests
  outputPath: guidelines/how-to-write-php-code.md
  sources:
    - type: url
      urls:
          - https://.../php-best-practices/
          - https://.../phpunit-best-practices/
          - https://.../php-spiral-testing/
```

The result might be:

```markdown
<instruction>
There are best guidelines in this document. Look at them and read those which are matched with your tasks.
</instruction>

<document>
Title: How to write PHP code
Description: use this guideline in any case when you need to write PHP code
File: guidelines/how-to-write-php-code.md
</document>

<document>
Title: How to write PHP tests
File: guidelines/how-to-write-php-code.md
</document>
```

Any idea?
