### ISSUE TITLE
Implement Template-based Prompt Extension System

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#180]
Add support for template-based prompts in the MCP Server, allowing prompts to extend other prompts with variable substitution. This will enable creating reusable prompt templates that can be customized for different use cases.

## Background
The current prompt system allows creating prompts with variables that can be filled at runtime, but lacks the ability to create template prompts that other prompts can extend and customize. This feature would improve code reuse and make prompt management more efficient.

## Requirements

1. Add a new prompt type: `template`
   - Templates should not appear in the general prompts list
   - Templates can only be used as a base for other prompts/templates

2. Add extension capability to prompts
   - A prompt/template can extend one or more templates
   - Support variable substitution in the extension

3. Variable substitution
   - Allow substituting variables in templates with values from the extending prompt
   - Support nested variable replacement patterns like `{{title}}`, `{{description}}`

4. Inheritance chain
   - Allow templates to extend other templates, creating an inheritance chain
   - Ensure proper resolution of variables through the chain

## Example Configuration

```yaml
prompts:
  - id: template-issue
    description: Create a new issue in the repository
    type: template
    messages:
      - role: user
        content: "Create a new issue with the following title and description: {{title}} {{description}}"

  - id: bug-issue
    description: Create a new bug issue
    type: prompt
    extend:
      - id: template-issue
        arguments:
          title: 'Bug: {{title}}'
          description: '{{description}}'

  - id: feature-issue
    description: Create a new feature issue
    type: prompt
    extend:
      - id: template-issue
        arguments:
          title: 'Feature: {{title}}'
          description: '{{description}}'

  # Example of template extending another template
  - id: template-complex-issue
    type: template
    extend:
      - id: template-issue
        arguments:
          title: '{{type}}: {{title}}'
          description: '{{description}} \n\n**Priority**: {{priority}}'
```

## Technical Considerations
- Maintain backward compatibility with existing prompts
- Default type should be `prompt` if not specified
- Implement proper error handling for circular dependencies or missing templates
- Templates should not be directly available through the API, only the prompts that extend them
