### ISSUE TITLE
Prompt Tagging and Filtered Import System

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#185]
Implement a tagging system for prompts and enhance the import functionality to allow filtering prompts by IDs and tags. This will enable users to better organize their prompts and selectively import only the prompts they need from external sources.

## Motivation
Currently, users must import entire prompt collections without the ability to filter, leading to:
- Cluttered prompt registries with unused prompts
- Difficulty finding relevant prompts for specific use cases
- Challenges in organizing and categorizing prompts
- Inability to selectively import from public prompt repositories

### 1. Basic Tag Implementation
Add the ability to assign tags to prompts in the YAML configuration:

```yaml
prompts:
  - id: creative-writing
    description: "Helps generate creative writing pieces"
    tags: ["writing", "creative", "content-generation"]
    messages:
      - role: user
        content: "You are a creative writing assistant..."
```

### 2. ID-Based Import Filtering
Allow importing specific prompts by their IDs:

```yaml
imports:
  - url: "https://prompts-repository.example.com/prompts.yaml"
    type: url
    filter:
      ids: ["python-helper", "php-debug", "js-refactor"]
```

### 3. Tag-Based Import with Logic
Support filtering imports by tags with include/exclude logic:

```yaml
imports:
  - path: "./local-prompts.yaml"
    type: local
    filter:
      tags:
        include: ["coding", "debugging"]
        exclude: ["advanced"]
      match: "any"  # can be "all" for AND logic
```

## User Experience

1. **CLI:**
   - Support for listing prompts by tags: `list-prompts --tags=coding,debugging`
   - Import command with filtering: `import-prompts --source=url --tags=coding`

2. **Configuration:**
   - Allow tags definition in existing YAML files
   - Support import configuration in project config files

Here are additional examples to illustrate how the tagging and import features could be used in various scenarios:

### Domain-Specific Tags

```yaml
prompts:
  - id: data-analysis-prompt
    description: "Analyzes tabular data and provides statistical insights"
    tags: ["data", "analysis", "statistics"]
    messages:
      - role: user
        content: "You are a data analyst assistant..."

  - id: code-review-php
    description: "Reviews PHP code for best practices and security issues"
    tags: ["code-review", "php", "security"]
    messages:
      - role: user
        content: "You are a PHP code review assistant..."
```

### Purpose-Based Tags

```yaml
prompts:
  - id: brainstorming-assistant
    description: "Helps generate creative ideas for a given problem"
    tags: ["creativity", "brainstorming", "ideation"]
    messages:
      - role: user
        content: "You are a brainstorming assistant..."

  - id: summarization-prompt
    description: "Summarizes long texts into concise points"
    tags: ["summarization", "content", "productivity"]
    messages:
      - role: user
        content: "You are a summarization assistant..."
```

### Skill Level Tags

```yaml
prompts:
  - id: beginner-python
    description: "Explains Python concepts for beginners"
    tags: ["python", "beginner", "tutorial"]
    messages:
      - role: user
        content: "You are a Python tutor for beginners..."

  - id: advanced-ml-prompt
    description: "Discusses advanced machine learning concepts"
    tags: ["machine-learning", "advanced", "technical"]
    messages:
      - role: user
        content: "You are an advanced machine learning expert..."
```
