### ISSUE TITLE
GitLab Source Implementation

### ISSUE THREAD

**Issue by timz** [context-hub/generator#186]
We need to implement a GitLab source component that mirrors the functionality of the existing GitHub source implementation. This will allow users to fetch code and documentation from both public and private GitLab repositories, supporting both gitlab.com and self-hosted GitLab instances.

## Key Requirements

1. **API Integration**:
    - Connect to GitLab repositories using the GitLab API v4
    - Support authentication via personal access tokens
    - Support both gitlab.com and self-hosted GitLab instances through custom server URLs
    - Handle both public and private repositories

2. **Repository Access**:
    - Support fetching from specific branches or tags
    - Support browsing directory structures
    - Retrieve file contents

3. **Filtering Capabilities**:
    - Filter by file path patterns
    - Filter by file name patterns
    - Filter by file content (includes/excludes)
    - Support exclusion patterns

4. **Output Features**:
    - Generate tree view of repository structure
    - Apply content modifiers to retrieved files

5. **Architecture**:
    - Integrate with the existing source registry
    - Follow the same architecture pattern as the GitHub source
    - Support environment variable interpolation for tokens
    - Allow for global GitLab server configurations in a settings section
    - Enable per-source server configurations to override global settings

### Self-hosted GitLab Instance

```yaml
documents:
  - description: Self-hosted GitLab Documentation
    outputPath: docs/self-hosted-gitlab.md
    sources:
      - type: gitlab
        description: Self-hosted GitLab Project
        repository: group/project
        branch: main
        server:
          url: https://gitlab.test.com
          token: ${TEST_GITLAB_TOKEN}
          headers:
            X-Custom-Header: custom-value
        sourcePaths:
          - src
        filePattern: "*.php"
```

### Global Server Configuration

```yaml
settings:
  gitlab:
    servers:
      default:
        url: https://gitlab.com
        token: ${DEFAULT_GITLAB_TOKEN}
      company:
        url: https://gitlab.example.com
        token: ${COMPANY_GITLAB_TOKEN}

documents:
  - description: Using Global GitLab Configuration
    outputPath: docs/gitlab-global-config.md
    sources:
      - type: gitlab
        description: Company GitLab Project
        server: company # References the server configuration in settings
        repository: group/project
        sourcePaths:
          - src
```

## Parameter Specifications

|Parameter|Type|Default|Description|
|---|---|---|---|
|type|string|required|Must be "gitlab"|
|description|string|""|Human-readable description of the source|
|repository|string|required|GitLab repository in format "group/project"|
|serverUrl|string|"https://gitlab.com"|Base URL for the GitLab instance|
|server|string|null|Reference to a server configuration in settings.gitlab.servers|
|sourcePaths|string\|array|required|Path(s) within the repository to include|
|branch|string|"main"|Branch or tag to fetch from|
|filePattern|string\|array|"_._"|File pattern(s) to match|
|excludePatterns|array|[]|Patterns to exclude files|
|notPath|array|[]|Alternative name for excludePatterns|
|path|string\|array|[]|Patterns to include only files in specific paths|
|contains|string\|array|[]|Patterns to include only files containing specific content|
|notContains|string\|array|[]|Patterns to exclude files containing specific content|
|showTreeView|boolean|true|Whether to display a directory tree visualization|
|gitlabToken|string|null|GitLab API token for private repositories (can use env var pattern ${TOKEN_NAME})|
|modifiers|array|[]|Content modifiers to apply|
|tags|array|[]|List of tags for this source|

### Multiple Source Paths

```yaml
documents:
  - description: Multiple GitLab Directories
    outputPath: docs/multiple-dirs.md
    sources:
      - type: gitlab
        description: Multiple Source Directories
        repository: group/project
        sourcePaths:
          - src/Controllers
          - src/Models
          - config
        filePattern: "*.php"
        showTreeView: true
```

### Multiple File Patterns

```yaml
documents:
  - description: Multiple File Types
    outputPath: docs/multiple-types.md
    sources:
      - type: gitlab
        description: Multiple File Types
        repository: group/project
        sourcePaths:
          - src
        filePattern:
          - "*.php"
          - "*.json"
          - "*.md"
        showTreeView: true
```

### Content-Based Filtering

```yaml
documents:
  - description: Service Classes
    outputPath: docs/services.md
    sources:
      - type: gitlab
        description: Service Classes
        repository: group/project
        sourcePaths:
          - src
        contains:
          - class Service
          - implements ServiceInterface
        notContains:
          - @deprecated
          - @internal
        filePattern: "*.php"
        showTreeView: true
```
