### ISSUE TITLE
Add new source type + tool for context7

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#200]
Add support for Context7 documentation service as a new source type in CTX, allowing users to retrieve specific documentation content from Context7-indexed repositories with topic filtering and token limiting capabilities.

## Background
CTX currently supports various source types (file, URL, GitHub, etc.) to build context for LLM interactions. Context7 provides a specialized service for accessing documentation from various libraries and repositories with powerful filtering capabilities. Integrating Context7 would enhance CTX's ability to provide targeted, relevant documentation content to LLM assistants.

## Proposed Solution
Add a new "docs" source type and a related "docs-search" tool that interfaces with Context7's API to:
1. Search available documentation libraries
2. Retrieve specific content based on topics
3. Limit content by token count

### New `docs` Source Type
- **Configuration Example**:
  ```yaml
  - description: 'Project structure overview'
    outputPath: project-structure.md
    overwrite: true
    sources:
      - type: docs
        library: "laravel/docs"  # Repository ID
        topic: controller        # Search topic/keyword
        tokens: 600              # Token limit
        description: "Laravel controller documentation"  # Optional description
        tags: ["laravel", "docs"]  # Optional tags
  ```

### New `docs-search` Tool
- Allow users to search for available documentation libraries through the Context7 API
- Endpoint: `https://context7.com/api/v1/search?query=SEARCH_TERM`
- Return formatted results with library details

### Implementation Components Needed
1. **DocsSource class** - Define the structure for the new source type
2. **DocsSourceFactory** - Create DocsSource instances from configuration
3. **DocsSourceFetcher** - Handle content retrieval from Context7
4. **DocsSearchTool** - MCP tool for searching available libraries

### API Integration
- Create a dedicated Context7 client to handle API requests
- Support authentication if required by Context7
- Handle rate limiting and error responses appropriately

### Content Processing
- Support proper content formatting from Context7 responses
- Apply content modifiers similar to other source types
- Ensure proper error handling for unavailable libraries or topics

### Configuration Parameters
- **library** (required): The identifier for the documentation repository
- **topic** (required): Topic or keyword to filter content
- **tokens** (optional): Maximum token count to retrieve, default could be 500
- **description** (optional): Human-readable description for the source
- **tags** (optional): Array of tags for categorization

## User Experience
- Provide clear error messages when a library or topic is not found
- Include example configurations in documentation
- Show relevant information about token limits and available libraries

## Benefits
1. **Enhanced Documentation Access**: Targeted access to specific documentation segments
2. **Reduced Token Usage**: Ability to limit content size for more efficient context management
3. **Topic-Specific Content**: Focus on particular aspects of documentation instead of entire files
4. **Larger Knowledge Base**: Access to a wider range of libraries and frameworks without storing locally
