### ISSUE TITLE
Source-Specific Output Paths

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#70]
Currently, the Context Generator only supports document-level output paths. This means all sources within a document are compiled into a single output file. This feature request proposes adding support for source-specific output paths, allowing individual sources to be output to separate files.

## Current Behavior

In the current implementation, document configuration looks like:

```yaml
documents:
  - description: "API Documentation"
    outputPath: "docs/api.md"
    sources:
      - type: file
        sourcePaths: ["src/Api"]
        filePattern: "*.php"
      - type: text
        content: "# API Documentation"
```

All sources in a document are combined and output to the document's `outputPath`.

## Proposed Behavior

The proposed change would allow sources to specify their own `outputPath`, like:

```yaml
documents:
  - description: "API Documentation"
    outputPath: "docs/api.md" # Default for sources without their own outputPath
    sources:
      - type: file
        outputPath: "docs/api/models.md" # Source-specific output
        sourcePaths: ["src/Api/Models"]
        filePattern: "*.php"
      - type: file
        outputPath: "docs/api/controllers.md" # Source-specific output
        sourcePaths: ["src/Api/Controllers"]
        filePattern: "*.php"
      - type: text
        content: "# API Documentation"
```

### Implementation Strategy:

The document builder should have a collection of outputs (output path → content) instead of just a single output. This would allow it to collect content for different output paths and then write them all at once.

## Benefits

- More flexible document organization
- Ability to split large context files into modular components
- Easier maintenance of generated documentation
- Support for more complex documentation structures

## Example Use Case

Breaking down a monolithic API documentation into separate files for each component:

```yaml
documents:
  - description: "Source System Architecture"
    outputPath: "docs/source-system.md"
    sources:
      - type: file
        sourcePaths: ["src"]
        filePattern: "SourceInterface.php"
        description: "Core source interface defining the contract for all sources"
      - type: file
        outputPath: "docs/source-system/base-source.md"
        sourcePaths: ["src/Source"]
        filePattern: "BaseSource.php"
        description: "Base implementation with common functionality for all sources"
      - type: file
        outputPath: "docs/source-system/source-with-modifiers.md"
        sourcePaths: ["src/Source"]
        filePattern: "SourceWithModifiers.php"
        description: "Extended base source with modifier support"
```
