### ISSUE TITLE
Self-Updating Configuration via MC Tools

### ISSUE THREAD

**Issue by butschster** [context-hub/generator#96]
I propose to add an ability for the LLM to dynamically update the `context.yaml` (or `context.json`) configuration file based on user requests and automated refactoring needs.
The feature will include two key operations:

1. **Append New Contexts**  
Allow LLM to insert new `documents` or `sources` sections into `context.yaml` when the user requests to add a specific context (file, folder, Git diff, text, URL, Composer package, etc.).

2. **Restructure Configuration with Imports**  
Allow LLM to move part of the configuration from the main `context.yaml` to a separate subdirectory file and automatically add an `import` statement in the main config to keep the structure modular and maintainable.

---

### 1. Context Auto-Injection

**Behavior**:
- When the user asks:  
  _"Add documentation for `src/Service` directory to context"_,  
  the LLM can:
  - Check if a relevant `document` exists
  - If yes, append a new `source` block
  - If no, create a new `document` block
- Validate against duplication (do not add sources that already exist)
- Support all source types (`file`, `text`, `tree`, `github`, `composer`, `git_diff`, `url`)

**Example**:
When requested:
> Add file context for `src/Service`

The LLM will append:

```yaml
documents:
  - description: API Documentation
    outputPath: docs/api.md
    sources:
      - type: file
        description: Service Directory
        sourcePaths:
          - src/Service
        filePattern: "*.php"
```

---

### 2. Configuration Refactoring with Imports

**Behavior**:
- When requested:
  > Move all API-related contexts to `services/api/context.yaml`
- LLM will:
  - Extract all related `documents` and `sources` (by tag, description, or outputPath)
  - Move them to a new config file (e.g., `services/api/context.yaml`)
  - Add an `import` directive in the root `context.yaml`:

```yaml
import:
  - path: services/api/context.yaml
```

**Advanced behavior**:
- When project config exceeds X lines (config bloat), the LLM can suggest modularization automatically.
- Detect and prevent circular imports (already implemented in import mechanism).
